### ISSUE TITLE
Implement Registering a Dog as Lost (Backend)

### ISSUE THREAD

**Issue by nighthawkbravo** [se2-2021-tue-16-okulewicz/Project-Group-B#10]
- [x] Implement Lost Dog Model (Estimate: 0.5h)
- [x] Implement LostDogDataRepository (Estimate: 1h)
- [x] implement LostDogsService (Estimate: 1h)
- [x] Implement LostDogsController (Estimate: 1h)

Estimate: 3.5h

**Comment by Lank891** [comment]
Time spent: 12h: I took some time to setup in-memory database for backend tests, but most of the time was spent to talk with group C about many specification problems, especially with inconsistent data and API that resulted in many changes of the implementation.
