### ISSUE TITLE
Implement Sign-in (Backend)

### ISSUE THREAD

**Issue by nighthawkbravo** [se2-2021-tue-16-okulewicz/Project-Group-B#13]
- [x] Implement Login Service (Estimate: 0.5h)
- [x] Implement UserRepository (Estimate: 1h)
- [x] Implement UserController (Estimate: 1h)

Estimate: 2.5h

**Comment by pinola-b** [comment]
Before review, the implementation took me approx. 6 hours

**Comment by pinola-b** [comment]
Took me around 7 hours altogether.
