### ISSUE TITLE
Implement Sign-in (Frontend)

### ISSUE THREAD

**Issue by nighthawkbravo** [se2-2021-tue-16-okulewicz/Project-Group-B#15]
- [x] Create mockups (Estimate: 0.5h)
 - [x] Implement GUI (Estimate: 2h)
 - [x] Implement connection with backend (Estimate: 1h)

Estimate: 3.5h

**Comment by Lank891** [comment]
Time spent: about 5 hours
Why more? I added handling error in frontend (modal popup, especially unathorized response takes us to login screen), i added some kind of modal loading animation when we are waiting for server response, i added footer with github link and implemented local logout functionality that can be easily extended to make api request (it's already using async thunk)
